name: genot
channels:
  - conda-forge
dependencies:
  - pip:
      - absl-py==1.4.0
      - anndata==0.9.2
      - appdirs==1.4.4
      - array-record==0.4.0
      - asttokens==2.2.1
      - astunparse==1.6.3
      - backcall==0.2.0
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - chex==0.1.82
      - click==8.1.6
      - comm==0.1.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - debugpy==1.6.8
      - decorator==5.1.1
      - diffrax==0.4.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - entot==0.1.0
      - equinox==0.10.11
      - etils==1.4.1
      - executing==1.2.0
      - flatbuffers==23.5.26
      - flax==0.7.1
      - fonttools==4.42.0
      - gast==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.34
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.60.0
      - grpcio==1.56.2
      - h5py==3.9.0
      - idna==3.4
      - importlib-resources==6.0.0
      - ipykernel==6.25.0
      - ipython==8.14.0
      - jax==0.4.14
      - jaxlib==0.4.14+cuda12.cudnn89
      - jaxopt==0.7
      - jaxtyping==0.2.20
      - jedi==0.19.0
      - joblib==1.3.1
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - keras==2.13.1
      - kiwisolver==1.4.4
      - libclang==16.0.6
      - lineax==0.0.1
      - llvmlite==0.40.1
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - msgpack==1.0.5
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - nest-asyncio==1.5.7
      - networkx==3.1
      - numba==0.57.1
      - numpy==1.24.4
      - numpyro==0.13.2
      - opt-einsum==3.3.0
      - optax==0.1.7
      - orbax-checkpoint==0.3.2
      - ott-jax==0.4.3.dev22+gf275dc4
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - pathtools==0.1.2
      - patsy==0.5.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - platformdirs==3.10.0
      - promise==2.3
      - prompt-toolkit==3.0.39
      - protobuf==4.23.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.15.1
      - pynndescent==0.5.10
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rich==13.5.2
      - rsa==4.9
      - scanpy==1.9.3
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - seaborn==0.12.2
      - sentry-sdk==1.30.0
      - session-info==1.0.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - stack-data==0.6.2
      - statsmodels==0.14.0
      - stdlib-list==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-datasets==4.9.2
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - tensorflow-metadata==1.13.1
      - tensorstore==0.1.40
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - toml==0.10.2
      - toolz==0.12.0
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - typeguard==4.1.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - umap-learn==0.5.3
      - urllib3==1.26.16
      - wandb==0.15.9
      - wcwidth==0.2.6
      - werkzeug==2.3.6
      - wrapt==1.15.0
      - zipp==3.16.2
